name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install pods
        run: pod install

      - name: Build app
        run: |
          xcodebuild \
            -workspace WebApp.xcworkspace \
            -scheme WebApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/WebApp.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/WebApp.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-IPA
          path: build/WebApp.ipa
