name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: |
          cd WebApp/WebApp
          pod install

      - name: Build app (IPA)
        run: |
          cd WebApp/WebApp
          xcodebuild -workspace WebApp.xcworkspace \
                     -scheme WebApp \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/WebApp.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/WebApp.xcarchive \
                     -exportPath $PWD/build/export \
                     -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-IPA
          path: WebApp/WebApp/build/export/*.ipa
