name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Try pod install (non-blocking)
        run: pod install || true
        shell: bash

      - name: Build .xcodeproj
        run: |
          xcodebuild \
            -project SoulLandWebApp.xcodeproj \
            -scheme SoulLandWebApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/SoulLandWebApp.xcarchive \
            archive
        shell: bash

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/SoulLandWebApp.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist
        shell: bash

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SoulLandWebApp-IPA
          path: build/SoulLandWebApp.ipa
