name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install
        working-directory: WebApp

      - name: Build Archive
        run: |
          xcodebuild \
            -workspace WebApp.xcworkspace \
            -scheme SoulLandWebApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/WebApp/build/SoulLandWebApp.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM=""
        working-directory: WebApp

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/WebApp/build/SoulLandWebApp.xcarchive \
            -exportPath $PWD/WebApp/build \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO
        working-directory: WebApp

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SoulLandWebApp-IPA
          path: WebApp/build/*.ipa
